- name: copy backend files to server
  connection: local
  become: true
  copy:
      src: ~/project/artifact.tar.gz
      dest: ~/project/.circleci/artifact.tar.gz
- name: start npm
  connection: local
  shell: |
    cd .circleci
    tar -xzvf artifact.tar.gz -C .
    npm run build
    pm2 completion install
    pm2 stop default
    pm2 start npm -- start