- name: copy backend files to server
  connection: local
  become: true
  copy:
      src: ~/project/artifact.tar.gz
      dest: ~/project/.circleci/ansible/artifact.tar.gz
- name: start npm
  connection: local
  shell: |
    tar -xzvf artifact.tar.gz -C .
    cd artifact
    sudo npm install
    sudo npm install -g pm2
    pm2 stop default
    pm2 start package.json